# Generated by Django 5.0.14 on 2025-12-30 17:47

import django.db.models.deletion
from django.db import migrations, models

import wagtail.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("date", models.DateField(verbose_name="Post date")),
                ("intro", models.CharField(max_length=250)),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "technical_specs",
                    wagtail.fields.StreamField(
                        [("spec", 2)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Specification name (e.g., 'CPU', 'RAM', 'Display')",
                                    "max_length": 100,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Specification value (e.g., '8GB', '2.4GHz', '15.6 inches')",
                                    "max_length": 200,
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("spec_name", 0), ("spec_value", 1)]],
                                {},
                            ),
                        },
                        help_text="Technical specifications - translators can mark these to use original values",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(blank=True, help_text="A short tagline for the homepage", max_length=255),
                ),
                (
                    "body",
                    wagtail.fields.RichTextField(blank=True, help_text="Main content area with rich text"),
                ),
                (
                    "features",
                    wagtail.fields.StreamField(
                        [("feature", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Feature heading", "max_length": 100},
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Feature description"},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional image caption",
                                    "max_length": 200,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 0), ("paragraph", 1), ("image_caption", 2)]],
                                {},
                            ),
                        },
                        help_text="Feature blocks that can be individually marked as 'do not translate'",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
            },
            bases=("wagtailcore.page",),
        ),
    ]
